version: '3.8'

services:
  # Service Ollama pour l'IA
  ollama:
    image: ollama/ollama:latest
    container_name: pdf_analyzer_ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    environment:
      - OLLAMA_HOST=0.0.0.0
      - OLLAMA_DEBUG=INFO
      - OLLAMA_GPU_LAYERS=35  # Utiliser GPU pour toutes les couches
      - OLLAMA_FLASH_ATTENTION=true  # Optimisation de l'attention
      - OLLAMA_NUM_PARALLEL=4  # Parallélisation
      - OLLAMA_KEEP_ALIVE=5m  # Garder le modèle en mémoire
    runtime: nvidia
    restart: unless-stopped

  # Application principale
  app:
    build: .
    container_name: pdf_analyzer_app
    ports:
      - "8000:8000"
    volumes:
      - ./uploads:/app/uploads
      - ./outputs:/app/outputs
    environment:
      - OLLAMA_URL=http://ollama:11434
      - OLLAMA_MODEL=llama3
      - OLLAMA_TIMEOUT=30
      - MAX_RETRIES=3
      - RETRY_DELAY=2
    depends_on:
      - ollama
    restart: unless-stopped

  # Service pour télécharger le modèle Llama (optionnel)
  model-downloader:
    image: ollama/ollama:latest
    container_name: pdf_analyzer_model_downloader
    entrypoint: ["/bin/sh", "-c"]
    command: |
      "echo 'Attente du démarrage d''Ollama...' &&
       sleep 30 &&
       echo 'Téléchargement du modèle llama3...' &&
       OLLAMA_HOST=http://ollama:11434 ollama pull llama3 &&
       echo 'Modèle téléchargé avec succès!'"
    volumes:
      - ollama_data:/root/.ollama
    depends_on:
      - ollama
    restart: "no"

volumes:
  ollama_data:
    driver: local 