version: '3.8'

services:
  ollama:
    image: ollama/ollama:latest
    container_name: pdf_analyzer_ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    environment:
      - OLLAMA_DEBUG=INFO
      - OLLAMA_GPU_LAYERS=35  # Utiliser GPU pour toutes les couches
      - OLLAMA_FLASH_ATTENTION=true  # Optimisation de l'attention
      - OLLAMA_NUM_PARALLEL=4  # Parallélisation
      - OLLAMA_KEEP_ALIVE=5m  # Garder le modèle en mémoire
    runtime: nvidia
    networks:
      - pdf_analyzer_network
    restart: unless-stopped

  model-downloader:
    image: ollama/ollama:latest
    container_name: pdf_analyzer_model_downloader
    depends_on:
      - ollama
    environment:
      - OLLAMA_HOST=http://ollama:11434
    entrypoint: ["/bin/sh", "-c"]
    command: |
      "echo 'Attente du démarrage d''Ollama...' &&
       sleep 10 &&
       echo 'Téléchargement du modèle llama3...' &&
       ollama pull llama3 &&
       echo 'Modèle téléchargé avec succès!'"
    networks:
      - pdf_analyzer_network
    restart: on-failure

  app:
    build: .
    container_name: pdf_analyzer_app
    ports:
      - "8000:8000"
    volumes:
      - ./uploads:/app/uploads
      - ./outputs:/app/outputs
    depends_on:
      - ollama
    environment:
      - OLLAMA_URL=http://ollama:11434
      - OLLAMA_MODEL=llama3
      - OLLAMA_TIMEOUT=90  # Timeout réduit pour GPU
    networks:
      - pdf_analyzer_network
    restart: unless-stopped

volumes:
  ollama_data:

networks:
  pdf_analyzer_network:
    driver: bridge 